CREATE TABLE users (
    id UUID PRIMARY KEY NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    photo_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
